/// Flutter icons OpArtLab
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  OpArtLab
///      fonts:
///       - asset: fonts/OpArtLab.ttf
///
///
///
library;
import 'package:flutter/widgets.dart';

class OpArtLab {
  OpArtLab._();

  static const _kFontFam = 'OpArtLab';
  // static const _kFontPkg = null;

  static const IconData quarterSquare = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData quarterTriangle =
      IconData(0xe801, fontFamily: _kFontFam);
  static const IconData miniCircle = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData halfTriangle = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData halfCircle = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData circle = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData quarterCircle = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData recursionDepth =
      IconData(0xe807, fontFamily: _kFontFam);
  static const IconData recursionRatio =
      IconData(0xe808, fontFamily: _kFontFam);
  static const IconData shapes = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData pointiness = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData L = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData horizontalDrift =
      IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData verticalDrift = IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData O = IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData horizontalOffset =
      IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData verticalOffset =
      IconData(0xe810, fontFamily: _kFontFam);
  static const IconData wallpaperRatio =
      IconData(0xe811, fontFamily: _kFontFam);
  static const IconData lineHorizontal =
      IconData(0xe812, fontFamily: _kFontFam);
  static const IconData lineVertical = IconData(0xe813, fontFamily: _kFontFam);
  static const IconData lineDiagonalRight =
      IconData(0xe814, fontFamily: _kFontFam);
  static const IconData lineDiagonalLeft =
      IconData(0xe815, fontFamily: _kFontFam);
  static const IconData bulge = IconData(0xe816, fontFamily: _kFontFam);
  static const IconData sShape = IconData(0xe817, fontFamily: _kFontFam);
  static const IconData pipe = IconData(0xe818, fontFamily: _kFontFam);
  static const IconData squaredCircle = IconData(0xe819, fontFamily: _kFontFam);
}
